page_ctx={
    'overlap':{
        'link3d':'/media/HLT_D1/index.html',
        'menu_circle':'com-menu-circle-sm',
        'menu_vertical':'com-menu-vertical-d',
        'show_help':True
    },
    'xing_kong':{
        'link3d':'/media/HLT_DP/index.html',
        'menu_circle':'com-menu-circle-lg',
        'menu_vertical':'com-menu-vertical-d',
        'page2d':'xing_kong_2d',
        'crt_btn':'d1',
    },
    'xing_kong_2d':{
        'img_url':'/static/images/2d3d/pic_星空独栋户型图.jpg',
        'menu_circle':'com-menu-circle-2d',
        'po_3d':'xing_kong_po'
    },
    'xing_kong_po':{
        'link3d':'/media/HLT_DP/index.html',
        'menu_circle':'com-menu-circle',
        'menu_vertical':'com-menu-vertical',
    },
    'xing_yue':{
        'link3d':'/media/HLT_DP/index.html',
        'menu_circle':'com-menu-circle-lg',
        'menu_vertical':'com-menu-vertical-d',
        'page2d':'xing_yue_2d',
        'crt_btn':'d2',
    },
    'xing_yue_2d':{
        'img_url':'/static/images/2d3d/pic_星悦环幕首层户型图.jpg',
        'menu_circle':'com-menu-circle-2d',
        'po_3d':'xing_yue_po'
    },
    'xing_yue_po':{
        'link3d':'/media/HLT_DP/index.html',
        'menu_circle':'com-menu-circle',
        'menu_vertical':'com-menu-vertical',
    },
    'xing_hai':{
        'link3d':'/media/HLT_DP/index.html',
        'menu_circle':'com-menu-circle-lg',
        'menu_vertical':'com-menu-vertical-d',
        'page2d':'xing_hai_2d',
        'crt_btn':'d3',
    },
    'xing_hai_2d':{
        'img_url':'/static/images/2d3d/pic_星海花园首层.jpg',
        'menu_circle':'com-menu-circle-2d',
        'po_3d':'xing_hai_po'
    },
    'xing_hai_po':{
        'link3d':'/media/HLT_DP/index.html',
        'menu_circle':'com-menu-circle',
        'menu_vertical':'com-menu-vertical',
    },
    
    'tall_buiding_2d':{
        'img_url':'/static/images/2d3d/pic_高层户型图.jpg',
        'menu_circle':'com-menu-circle-2d',
        'po_3d':'xing_kong_po'
    },
    'yang_fang_2d':{
        'img_url':'/static/images/2d3d/pic_洋房户型图.jpg?v=1',
        'menu_circle':'com-menu-circle-2d',
        'po_3d':'xing_kong_po'
    }
}